import Head from 'next/head';
import React from 'react';

const Header = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1 className='title'>퀴즈 앱</h1>
    </div>
  );
};

export default Header;
